# Training Dataset and Optimization Parameters
num_training_epochs : 12       # Num. times loop over complete training dataset
batch_size_train : 64
batch_size_test : 1000
learning_rate : 0.01
momentum : 0.5
log_interval : 10
image_size : 24               # px

# PyTorch Backend Parameters
random_seed : 1
torch_backend_cudnn_enabled : False

